pipeline {
    agent any

    environment {
        IMAGE_NAME = "khaola15/greenshop-web:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/khaolakkkkk/greenshop-hackathon.git', 
                    credentialsId: 'github_id'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'cp -r /home/ubuntu/greenshop-docker/greenshop ./docker/'
                    sh 'DOCKER_BUILDKIT=0 docker build -t $IMAGE_NAME docker'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'docker_hub_id', 
                        usernameVariable: 'DOCKER_USER', 
                        passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin'
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh '''
                    cd docker
                    docker compose down || true
                    docker rm -f greenshop-db || true
                    docker rm -f greenshop-web || true
                    docker compose up -d --build
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment Successful"
        }
        failure {
            echo "Deployment Failed"
        }
    }
}

